
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1VFx3MdkK0ZGKWB7ByPSGyYjflnTS0v0',
    appId: '1:472201750510:web:d946aa4371310d5bbe10ff',
    messagingSenderId: '472201750510',
    projectId: 'ecomm-18247',
    authDomain: 'ecomm-18247.firebaseapp.com',
    databaseURL: 'https://ecomm-18247-default-rtdb.firebaseio.com',
    storageBucket: 'ecomm-18247.appspot.com',
    measurementId: 'G-VJ0CQ8DTTD',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhKuAgbA3edPT6x_uZ3xKya2QurPj1eXE',
    appId: '1:472201750510:android:3c91c37a652319d8be10ff',
    messagingSenderId: '472201750510',
    projectId: 'ecomm-18247',
    databaseURL: 'https://ecomm-18247-default-rtdb.firebaseio.com',
    storageBucket: 'ecomm-18247.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWHT51CLF7c900xdIv838CZnLkXk5F-ec',
    appId: '1:472201750510:ios:5b274f2544e08bc3be10ff',
    messagingSenderId: '472201750510',
    projectId: 'ecomm-18247',
    databaseURL: 'https://ecomm-18247-default-rtdb.firebaseio.com',
    storageBucket: 'ecomm-18247.appspot.com',
    iosClientId: '472201750510-6mqs6mqqro6jg00jgejmp5mk7bjupkvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommadmin',
  );



}